version: '3'

services:
  client-server:
    container_name: client_container
    image: pkiposmet/yolo-client-server:1.1.0
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    stdin_open: true
    networks:
      frontend-net:
        ipv4_address: 172.51.0.101
    depends_on:
      - backend-server

  backend-server:
    container_name: backend_container
    image: pkiposmet/yolo-backend-server:1.0.0
    ports:
      - 5001:5001
    environment:
      PORT: 5001
      DATABASE_URL: 'mongodb://backend:backend@172.100.0.101:27017'
    networks:
      backend-net:
        ipv4_address: 172.100.0.100
      frontend-net:
        ipv4_address: 172.51.0.100
    depends_on:
      - database
  database:
    container_name: backend_database
    ports:
      - 27017:27017
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: backend
      MONGO_INITDB_ROOT_PASSWORD: backend
    networks:
      backend-net:
        ipv4_address: 172.100.0.101
    volumes:
        - backend_volume:/data/db
networks:
    backend-net:
      ipam:
        driver: default
        config:
        - subnet: 172.100.0.0/16
    frontend-net:
      ipam:
        driver: default
        config:
        - subnet: 172.51.0.0/16
volumes:
  backend_volume:
