version: '3.8'

services:
  client-server:
    container_name: client_c1
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      PORT: 3000

  backend-server:
    container_name: backend_c1
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      PORT: 5001
      DATABASE_URL: 'mongodb+srv://PatrickB:PBarchok@cluster0.wwo1kqo.mongodb.net/?retryWrites=true&w=majority'
